# Traefik configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

api:
  dashboard: true

# Log level INFO|DEBUG|ERROR
log:
  level: INFO

# Configuring a buffer of 100 lines
accessLog:
  filePath: "/etc/traefik/access.log"
  bufferingSize: 100

entryPoints:
  # Not used in apps, but redirect everything from HTTP to HTTPS
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  # HTTPS endpoint, with domain wildcard
  websecure:
    address: :443
    http:
      tls:
        domains:
          - main: ublue.local
            sans:
              - "*.ublue.local"
      middlewares:
        - securityHeaders@file

providers:
  providersThrottleDuration: 2s
  # File provider for connecting things that are outside of docker / defining middleware
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true
  # Docker / Podman configuration backend
  docker:
    watch: true
    network: "ublue-os_forge"
    exposedByDefault: false
    endpoint: "unix:///var/run/podman.sock"
