---
- name: API authentication
  ansible.builtin.include_tasks:
    file: authentication.yml

- name: Add projects
  ansible.builtin.include_tasks:
    file: projects.yml

- name: Add keys
  ansible.builtin.include_tasks:
    file: keys.yml

- name: Add repositories
  ansible.builtin.include_tasks:
    file: repositories.yml

- name: Add environment
  ansible.builtin.include_tasks:
    file: environments.yml

- name: Add inventory
  ansible.builtin.include_tasks:
    file: inventories.yml

- name: Add templates
  ansible.builtin.include_tasks:
    file: templates.yml
